DEF_CMD (TYPE_NUM,          1,  "not a terminal")
DEF_CMD (TYPE_ID,           2,  "not a terminal")
DEF_CMD (TYPE_ASSIGN,       3,  "assignare")
DEF_CMD (TYPE_MUL,          4,  "mul")
DEF_CMD (TYPE_DIV,          5,  "partem")
DEF_CMD (TYPE_ADD,          6,  "crescere")
DEF_CMD (TYPE_SUB,          7,  "subtrahere")
DEF_CMD (TYPE_O_BRACKET,    8,  "aurora")
DEF_CMD (TYPE_C_BRACKET,    9,  "umbra")
DEF_CMD (TYPE_O_F_BRACKET,  10, "salve")
DEF_CMD (TYPE_C_F_BRACKET,  11, "vale")
DEF_CMD (TYPE_IF,           12, "inceptus")
DEF_CMD (TYPE_ELSE,         13, "cruciatus")
DEF_CMD (TYPE_SEMICOLON,    14, "ora")
DEF_CMD (TYPE_WHILE,        15, "cursus")
DEF_CMD (TYPE_RETURN,       16, "cessim")
DEF_CMD (TYPE_GR_OR_EQ,     '>=', ">=")
DEF_CMD (TYPE_LESS_OR_EQ,   '<=', "<=")
DEF_CMD (TYPE_LOG_AND,      '&&', "&&")
DEF_CMD (TYPE_LOG_OR,       '||', "||")